chore: notice for https://github.com/aws/aws-cdk/issues/27928
cdklabs/aws-cdk-notices pull request #326
Opened 2023-11-15 23:15 UTC by kaizencc

2023-11-15 23:15 UTC, kaizencc commented on data/notices.json
> +      "schemaVersion": "1"
```suggestion
      "schemaVersion": "1"
    }
```

2023-11-15 23:27 UTC, vinayak-kukreja approved these changes

2023-11-15 23:28 UTC, vinayak-kukreja requested changes

2023-11-15 23:28 UTC, vinayak-kukreja commented on data/notices.json
> +      "overview": "",
No overview?

2023-11-15 23:54 UTC, kaizencc commented on data/notices.json
> +      "title": "(elasticloadbalancingv2) applicationLoadBalancer fails with \"RuntimeError: TypeError: Cannot read properties of undefined\"",
```suggestion
      "title": "(elasticloadbalancingv2) applicationLoadBalancer fails with \"RuntimeError: TypeError: Cannot read properties of undefined\" on imported buckets",
```

2023-11-15 23:57 UTC, kaizencc commented on data/notices.json
> +      "overview": "",
```suggestion
      "overview": "A dependency on the bucket policy when using access logs was added to fix a circular dependency issue, but the bucket policy does not exist for imported buckets resulting in synth-time error (bucket.node.defaultChild is undefined).",
```

2023-11-15 23:57 UTC, kaizencc commented on data/notices.json
> +      "overview": "A dependency on the bucket policy when using access logs was added to fix a circular dependency issue, but the bucket policy does not exist for imported buckets resulting in synth-
```suggestion
      "overview": "A dependency on the bucket policy when using access logs was added to fix a circular dependency issue, but the bucket policy does not exist for imported buckets resulting in synth-time error.",
```

2023-11-16 00:12 UTC, vinayak-kukreja approved these changes

2023-11-30 16:27 UTC, merged